import { Link } from "@tanstack/react-router";
import { Linkedin, Mail } from "lucide-react";
import { Container } from "./container";
import { COMPANY } from "@/lib/company";
import logoAsset from "@/assets/clm-logo.svg.asset.json";
import { Button } from "@/components/ui/button";

export function SiteFooter() {
 const groups = [{title:"Solutions", links:[{to:"/offres",label:"Nos solutions"},{to:"/sante-environnement",label:"Santé & Environnement"},{to:"/emissions-performance",label:"Émissions & Performance"},{to:"/cas-clients",label:"Cas clients"}]},{title:"Ressources",links:[{to:"/technologie",label:"Technologie"},{to:"/gaz-mesurables",label:"Gaz mesurables"},{to:"/blog",label:"Blog"},{to:"/faq",label:"FAQ"},{to:"/en/brochure",label:"English brochure"}]}] as const;
 return <footer className="bg-footer"><Container className="py-12"><div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-[1.4fr_1fr_1fr_1.2fr]"><div><Link to="/" className="flex items-center gap-2"><img src={logoAsset.url} alt="CLM Industry" className="h-8 w-auto" width="40" height="40"/><strong className="uppercase">CLM Industry</strong></Link><p className="mt-5 max-w-xs text-sm leading-relaxed text-muted-foreground">Identification, mesure et surveillance des émissions de gaz industriels sur site.</p><p className="mt-4 text-xs leading-relaxed text-muted-foreground">{COMPANY.legalName}<br/>{COMPANY.address}</p></div>{groups.map(g=><nav key={g.title} aria-label={g.title}><h2 className="mb-5 text-xs font-semibold uppercase text-accent-light">{g.title}</h2><ul className="space-y-3">{g.links.map(l=><li key={l.to}><Link to={l.to} className="text-sm text-muted-foreground hover:text-accent-light">{l.label}</Link></li>)}</ul></nav>)}<div><h2 className="mb-5 text-xs font-semibold uppercase text-accent-light">Contact</h2><a href={`mailto:${COMPANY.email}`} className="text-sm hover:text-accent-light">{COMPANY.email}</a><div className="my-5 flex gap-3"><Button asChild variant="outline" size="icon" className="rounded-full"><a href={`mailto:${COMPANY.email}`} aria-label="Nous écrire"><Mail/></a></Button><Button asChild variant="outline" size="icon" className="rounded-full"><a href="https://www.linkedin.com/company/c-l-m-industry/" target="_blank" rel="noopener noreferrer" aria-label="CLM Industry sur LinkedIn"><Linkedin/></a></Button></div><Button asChild><Link to="/contact" hash="creneau">Prendre rendez-vous</Link></Button></div></div><div className="mt-10 flex flex-wrap justify-between gap-4 border-t border-border pt-6 text-xs text-muted-foreground"><div className="flex flex-wrap gap-5"><Link to="/mentions-legales" className="hover:text-accent-light">Mentions légales</Link><Link to="/politique-de-confidentialite" className="hover:text-accent-light">Politique de confidentialité</Link></div><span>Membre La French Fab · © {new Date().getFullYear()} CLM Industry</span></div></Container></footer>;
}
